### PR TITLE
Added description and screenshot files

### PR DESCRIPTION
**Pull request by ExcaliburZero**
Added a description and screenshot file that will be used by the Mod tab of the main menu of Minetest.

### CODE REVIEW

**Comment by BlockMen** [comment]
The screenshot should be in 4:3 format. IIRC he "frame"is sized that way in Mainmenu

**Comment by ExcaliburZero** [comment]
@BlockMen 
I've heard that the ratio should be 4:3, but when I actually checked the ratio at which the screenshot is displayed in the mods tab of the main menu it was 3:2.

Source: (https://github.com/minetest/minetest/blob/990a96578f20244626b6b9f67f8e79a7e2e614ea/builtin/mainmenu/tab_mods.lua#L64)

~~~
"image[5.5,0;3,2;" .. core.formspec_escape(modscreenshot) .. "]"
~~~

**Comment by BlockMen** [comment]
@ExcaliburZero 3:2 is the same ratio as 4:3 ;)
So whatever you call it, the screenshot is too wide

**Comment by ExcaliburZero** [comment]
Okay, there, that should do it.

**Pull request merged**
